# Generated by Django 3.2 on 2024-01-18 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='진료과목 이름')),
                ('search_name', models.CharField(max_length=128, verbose_name='검색용 이름')),
                ('is_reimbursement', models.BooleanField(default=True, verbose_name='급여여부')),
            ],
            options={
                'verbose_name': '진료과',
                'verbose_name_plural': '진료과들',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='의사 이름')),
                ('hospital_name', models.CharField(max_length=128, verbose_name='병원 이름')),
                ('department_set', models.ManyToManyField(related_name='doctor_set', to='doctor.Department', verbose_name='진료과')),
            ],
            options={
                'verbose_name': '의사',
                'verbose_name_plural': '의사들',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='환자 이름')),
            ],
            options={
                'verbose_name': '환자',
                'verbose_name_plural': '환자들',
            },
        ),
        migrations.CreateModel(
            name='OpenHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_time', models.TimeField(blank=True, null=True, verbose_name='개점시간')),
                ('closed_time', models.TimeField(blank=True, null=True, verbose_name='폐점시간')),
                ('day_type', models.PositiveSmallIntegerField(choices=[(0, '월요일'), (1, '화요일'), (2, '수요일'), (3, '목요일'), (4, '금요일'), (5, '토요일'), (6, '일요일'), (7, '점심시간'), (8, '공휴일')], verbose_name='요일')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor', verbose_name='의사')),
            ],
            options={
                'verbose_name': '영업시간',
                'verbose_name_plural': '영업시간들',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_apply', models.BooleanField(default=False, verbose_name='수락 여부')),
                ('request_date', models.DateTimeField(verbose_name='진료 요청 시간')),
                ('expired_date', models.DateTimeField(verbose_name='진료 요청 만료 시간')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor', verbose_name='의사')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.patient', verbose_name='환자')),
            ],
            options={
                'verbose_name': '진료 요청',
                'verbose_name_plural': '진료 요청들',
            },
        ),
    ]
